### ISSUE TITLE
QR Stopped

### ISSUE THREAD

**Issue by yogapamungkas96** [fawwaz37/whatsapp-gateway#10]
When you have scanned the qr code, a few moments later the log appears :
[APP] 15/05/23 11:17:05 Connection Database has been established Successfully
[APP] 15/05/23 11:17:05 Re-Sync Database
[APP] 15/05/23 11:17:05 App Listening at http://localhost:8080
[SYS] [Session: session_1] Open the browser, a qr has appeared on the website, scan it now!
1
Socket Disconnect
Socket Disconnect
Socket Disconnect
[SYS] [Session: session_1] Open the browser, a qr has appeared on the website, scan it now!
1
session_1 6288808037135
[SYS] [Session: session_1] Restart Required, Restarting...
Socket Disconnect
[SYS] 15/05/23 11:17:42 [Session: session_1] Session is Now Connected - Baileys Version 2,2228,8, isLatest : false
[SYS] [Session: session_1] Open the browser, a qr has appeared on the website, scan it now!
2
[SYS] [Session: session_1] Open the browser, a qr has appeared on the website, scan it now!
3
Count : 3, QR Stopped!

**Comment by fawwaz37** [comment]
Restart the program and try again to scan the QR code.
