### ISSUE TITLE
deploy to cpanel

### ISSUE THREAD

**Issue by galangw** [fawwaz37/whatsapp-gateway#5]
how to deploy this script on shared hosting ?

**Comment by itzmail** [comment]
it can be deploy on shared hosting?

**Comment by herusuandana** [comment]
Yeah> it can be deploy on shared hosting?

**Comment by Rapidak** [comment]
anyone please share db file

**Comment by fawwaz37** [comment]
To deploy the code on CPanel, convert it to CommonJS format.
